{
    "name": "Daisy Agency",
    "version": "19.0.5.4.2",
    "category": "Productivity",
    "summary": "AI agents as first-class Odoo users with livechat auto-response, error handler, and RTSP camera feeds",
    "author": "DaisyERP",
    "license": "LGPL-3",
    "depends": ["web", "daisydo_livechat", "im_livechat", "mail", "project", "base_setup", "hr", "resource", "daisy_error_handler"],
    "data": [
        "security/agent_security.xml",
        "security/ir.model.access.csv",
        "wizard/agent_import_views.xml",
        "wizard/create_agent_for_user_views.xml",
        "views/daisy_agent_feed_views.xml",
        "views/daisy_agent_job_views.xml",
        "views/daisy_agent_views.xml",
        "views/daisy_provisioning_views.xml",
        "views/daisy_agent_menus.xml",
        "views/res_config_settings_views.xml",
        "data/daisy_agent_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "daisydo_agents/static/src/js/feed_viewer.js",
            "daisydo_agents/static/src/xml/feed_viewer.xml",
            "daisydo_agents/static/src/js/feed_call_button.js",
            "daisydo_agents/static/src/xml/feed_call_button.xml",
            "daisydo_agents/static/src/js/feed_rtsp_out.js",
            "daisydo_agents/static/src/xml/feed_rtsp_out.xml",
            "daisydo_agents/static/src/css/feed_viewer.css",
        ],
    },
    "auto_install": False,
}
