#!/bin/bash
# ============================================================
# DaisyDo Theme Generator
# ============================================================
# Generates SCSS files with custom colors from env vars.
# Called by fix-config.sh at container startup.
#
# Environment Variables:
#   ODOO_BRAND_PRIMARY   - Primary brand color (default: #00954c)
#   ODOO_BRAND_HOVER     - Hover state color (auto-derived if unset)
#   ODOO_BRAND_ACTIVE    - Active/pressed state color (auto-derived)
#   ODOO_BRAND_ACCENT    - Accent/secondary color (default: #dac554)
#   ODOO_BRAND_BG        - Light background color (auto-derived)
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRIMARY_VARS_FILE="$SCRIPT_DIR/static/src/scss/primary_variables.scss"
THEME_FILE="$SCRIPT_DIR/static/src/scss/theme.scss"
WEBSITE_FILE="$SCRIPT_DIR/static/src/scss/website.scss"

# ============================================================
# HELPER FUNCTIONS
# ============================================================

hex_to_rgb() {
  local hex="${1#\#}"
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))
  echo "$r, $g, $b"
}

hex_to_r() { local hex="${1#\#}"; echo $((16#${hex:0:2})); }
hex_to_g() { local hex="${1#\#}"; echo $((16#${hex:2:2})); }
hex_to_b() { local hex="${1#\#}"; echo $((16#${hex:4:2})); }

# Compute relative luminance (0-255 scale approximation)
luminance() {
  local r=$(hex_to_r "$1")
  local g=$(hex_to_g "$1")
  local b=$(hex_to_b "$1")
  echo $(( (r * 299 + g * 587 + b * 114) / 1000 ))
}

# Darken a hex color by a percentage (0-100)
darken() {
  local hex="${1#\#}"
  local pct=$2
  local factor=$(( 100 - pct ))
  local r=$(( (16#${hex:0:2}) * factor / 100 ))
  local g=$(( (16#${hex:2:2}) * factor / 100 ))
  local b=$(( (16#${hex:4:2}) * factor / 100 ))
  printf "#%02x%02x%02x" "$r" "$g" "$b"
}

# Lighten a hex color toward white by a percentage (0-100)
lighten() {
  local hex="${1#\#}"
  local pct=$2
  local r=$(( (16#${hex:0:2}) + (255 - (16#${hex:0:2})) * pct / 100 ))
  local g=$(( (16#${hex:2:2}) + (255 - (16#${hex:2:2})) * pct / 100 ))
  local b=$(( (16#${hex:4:2}) + (255 - (16#${hex:4:2})) * pct / 100 ))
  printf "#%02x%02x%02x" "$r" "$g" "$b"
}

# ============================================================
# READ ENV VARS WITH DEFAULTS
# ============================================================

THEME_PRIMARY="${ODOO_BRAND_PRIMARY:-#00954c}"
THEME_ACCENT="${ODOO_BRAND_ACCENT:-#dac554}"

# Auto-derive hover/active/bg if not explicitly set
THEME_HOVER="${ODOO_BRAND_HOVER:-$(darken "$THEME_PRIMARY" 15)}"
THEME_ACTIVE="${ODOO_BRAND_ACTIVE:-$(darken "$THEME_PRIMARY" 30)}"
THEME_BG="${ODOO_BRAND_BG:-$(lighten "$THEME_PRIMARY" 90)}"

# Compute text-on-primary based on luminance
LUM=$(luminance "$THEME_PRIMARY")
if [ "$LUM" -gt 160 ]; then
  THEME_TEXT="#1a1a1a"
  THEME_TEXT_HOVER="#000000"
  THEME_TEXT_ALPHA="rgba(26, 26, 26, 0.9)"
else
  THEME_TEXT="#ffffff"
  THEME_TEXT_HOVER="#ffffff"
  THEME_TEXT_ALPHA="rgba(255, 255, 255, 0.9)"
fi

THEME_PRIMARY_RGB=$(hex_to_rgb "$THEME_PRIMARY")
THEME_ACCENT_RGB=$(hex_to_rgb "$THEME_ACCENT")

# ============================================================
# DISPLAY CONFIGURATION
# ============================================================

echo "============================================================"
echo "DaisyDo Theme Generator"
echo "============================================================"
echo ""
echo "Primary:      $THEME_PRIMARY"
echo "Hover:        $THEME_HOVER"
echo "Active:       $THEME_ACTIVE"
echo "Accent:       $THEME_ACCENT"
echo "BG:           $THEME_BG"
echo "Text:         $THEME_TEXT (luminance=$LUM)"
echo "Primary RGB:  $THEME_PRIMARY_RGB"
echo ""

# ============================================================
# GENERATE primary_variables.scss
# ============================================================

cat > "$PRIMARY_VARS_FILE" << PVSCSS
// DaisyDo Primary Variable Overrides
// Loaded BEFORE Odoo's primary_variables.scss so !default declarations are skipped.
//
// Generated by: generate-theme.sh
// Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

// Root brand colors
\$o-community-color: ${THEME_PRIMARY};
\$o-enterprise-color: ${THEME_PRIMARY};
\$o-enterprise-action-color: ${THEME_HOVER};

\$o-brand-odoo: ${THEME_PRIMARY};
\$o-brand-primary: ${THEME_PRIMARY};
\$o-brand-secondary: ${THEME_ACCENT};

// Bootstrap primary
\$primary: ${THEME_PRIMARY};

// Action color (buttons, active states, borders)
\$o-action: ${THEME_PRIMARY};

// Link color
\$o-main-link-color: ${THEME_HOVER};

// Required field border
\$o-input-border-required: ${THEME_HOVER};

// Active component states
\$o-component-active-bg: rgba(${THEME_PRIMARY_RGB}, 0.15);
\$o-component-active-border: ${THEME_PRIMARY};

// Navbar
\$o-navbar-background: ${THEME_PRIMARY};
\$o-navbar-border-bottom: 1px solid ${THEME_HOVER};
\$o-navbar-entry-color: ${THEME_TEXT_ALPHA};
\$o-navbar-entry-color--hover: ${THEME_TEXT_HOVER};
\$o-navbar-entry-color--active: ${THEME_TEXT_HOVER};
\$o-navbar-entry-bg--hover: rgba(0, 0, 0, 0.15);
\$o-navbar-entry-bg--active: rgba(0, 0, 0, 0.15);
\$o-navbar-brand-color: ${THEME_TEXT_ALPHA};
PVSCSS

echo "Generated: $PRIMARY_VARS_FILE"

# ============================================================
# GENERATE theme.scss (backend)
# ============================================================

cat > "$THEME_FILE" << SCSS
// DaisyDo Backend Theme — Component Styles
// Generated by: generate-theme.sh
// Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

// CSS Custom Properties (runtime overrides)
:root {
    --daisy-primary: ${THEME_PRIMARY};
    --daisy-secondary: ${THEME_ACCENT};
    --daisy-hover: ${THEME_HOVER};
    --daisy-active: ${THEME_ACTIVE};
    --daisy-bg: ${THEME_BG};
    --daisy-text-on-primary: ${THEME_TEXT};

    --o-brand-odoo: ${THEME_PRIMARY};
    --o-brand-primary: ${THEME_PRIMARY};
    --primary: ${THEME_PRIMARY};
    --primary-rgb: ${THEME_PRIMARY_RGB};
    --o-brand-secondary: ${THEME_ACCENT};
    --o-brand-primary-text: ${THEME_TEXT};

    // Navbar CSS custom properties (Odoo 19 reads these at runtime)
    --NavBar-entry-color: ${THEME_TEXT_ALPHA};
    --NavBar-entry-color--hover: ${THEME_TEXT_HOVER};
    --NavBar-entry-color--active: ${THEME_TEXT_HOVER};
    --NavBar-entry-backgroundColor: ${THEME_PRIMARY};
    --NavBar-entry-backgroundColor--hover: rgba(0, 0, 0, 0.08);
    --NavBar-entry-backgroundColor--active: rgba(0, 0, 0, 0.08);
    --NavBar-entry-backgroundColor--focus: rgba(0, 0, 0, 0.08);
    --NavBar-brand-color: ${THEME_TEXT_ALPHA};
}

// Backend navbar styling
.o_main_navbar {
    background-color: var(--daisy-primary) !important;
    border-bottom-color: var(--daisy-hover) !important;

    &, * {
        color: var(--daisy-text-on-primary) !important;
    }

    .o_menu_brand:hover,
    .o_menu_toggle:hover,
    .dropdown-toggle:hover,
    .nav-link:hover {
        color: ${THEME_TEXT_HOVER} !important;
        background-color: rgba(0, 0, 0, 0.1) !important;
    }

    // Menu section entries
    .o_menu_sections .o_nav_entry,
    .o_menu_sections .dropdown-toggle {
        background: var(--daisy-primary) !important;
        color: ${THEME_TEXT_ALPHA} !important;

        &:hover {
            background: rgba(0, 0, 0, 0.08) !important;
        }
    }
}

// Frontend website navbar
header#top nav.navbar {
    background-color: var(--daisy-primary) !important;

    &, a, span, .nav-link, .navbar-brand, .dropdown-toggle,
    .o_navlink_background, .fa {
        color: var(--daisy-text-on-primary) !important;
    }

    a:hover, .nav-link:hover, .dropdown-toggle:hover {
        color: ${THEME_TEXT_HOVER} !important;
    }
}

// Primary buttons
.btn-primary {
    background-color: var(--daisy-primary) !important;
    border-color: var(--daisy-hover) !important;
    color: var(--daisy-text-on-primary) !important;

    &:hover, &:focus, &:active {
        background-color: var(--daisy-hover) !important;
        border-color: var(--daisy-active) !important;
        color: var(--daisy-text-on-primary) !important;
    }
}

// Links
a.text-primary,
.text-primary {
    color: var(--daisy-hover) !important;
}

// Selection and focus highlights
.o_form_view .o_field_widget.o_field_highlight {
    background-color: rgba(${THEME_PRIMARY_RGB}, 0.1);
}

// Kanban headers and highlights
.o_kanban_header {
    border-color: var(--daisy-primary);
}

// Progress bars
.progress-bar {
    background-color: var(--daisy-primary);
}

// Login page
.oe_login_form .btn-primary {
    background-color: var(--daisy-primary) !important;
    border-color: var(--daisy-hover) !important;
    color: var(--daisy-text-on-primary) !important;
}

// Replace Odoo logo in navbar with DaisyERP
.o_main_navbar .o_menu_brand {
    &::before {
        content: "";
        display: inline-block;
        width: 28px;
        height: 28px;
        background-image: url("/daisydo_theme/static/src/img/logo.png");
        background-size: contain;
        background-repeat: no-repeat;
        background-position: center;
        margin-right: 8px;
        vertical-align: middle;
    }
}

// Hide Odoo branding text and Enterprise upsell elements
.o_brand_promotion,
.o_badge_remove,
[data-menu-xmlid="base.menu_management"] .o_menu_brand_icon {
    display: none !important;
}

// Enterprise upsell banners, upgrade buttons, and feature teasers
.o_enterprise_upsell,
.o_enterprise_upgrade,
.o_ee_cta,
.oe_database_expiration_panel,
.o_field_upgrade_boolean,
.o_upgrade_star,
.o_upgrade_extra,
[data-upgrade],
.o_upsell_bar {
    display: none !important;
}

// Settings page Enterprise feature labels and upgrade links
.o_settings_container .o_enterprise_label,
.o_settings_container .badge.text-bg-enterprise,
.o_settings_container a[href*='odoo.com'] {
    display: none !important;
}

// App switcher Enterprise labels
.o_home_menu .o_enterprise_label,
.o_app .badge.text-bg-enterprise {
    display: none !important;
}

// Login page logo styling
.oe_login_form img,
.o_login_box img {
    max-height: 100px;
    margin-bottom: 16px;
}

// Home menu app icons — tint to brand color
.o_home_menu .o_app .o_app_icon {
    border-radius: 12px;
    filter: hue-rotate(200deg) saturate(1.5) brightness(1.1);
}

// Company logo replacements across the web client
.o_company_logo img,
.o_menu_systray img.o_company_logo_img {
    content: url("/daisydo_theme/static/src/img/logo.png");
    object-fit: contain;
}

// Replace "Odoo" text in about dialog
.o_dialog .o_about_content .o_logo {
    content: url("/daisydo_theme/static/src/img/logo.png");
    max-width: 120px;
}
SCSS

echo "Generated: $THEME_FILE"

# ============================================================
# GENERATE website.scss (frontend)
# ============================================================

cat > "$WEBSITE_FILE" << SCSS
// DaisyDo Website — Frontend page styles
// Generated by: generate-theme.sh
// Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

// Custom CSS vars for website sections
:root {
    --daisy-light-bg: ${THEME_BG};
    --daisy-gradient: linear-gradient(135deg, ${THEME_PRIMARY} 0%, ${THEME_ACCENT} 100%);
}

// Section base: consistent spacing, full-width sections
section {
    padding: 80px 0;
}

// Hero sections: gradient bg, white text, centered
.s_cover,
.s_hero {
    background: var(--daisy-gradient);
    color: #fff;

    h1, h2, h3, p, .lead {
        color: #fff;
    }
}

// Light background utility
.bg-light-daisy {
    background: var(--daisy-light-bg);
}

// Card enhancements: shadows, rounded, equal-height, hover lift
.s_card.card,
.card.shadow-sm {
    border: none;
    border-radius: 12px;
    box-shadow: 0 2px 12px rgba(0, 0, 0, .08);
    transition: transform .2s, box-shadow .2s;
}

.s_card.card:hover,
.card.shadow-sm:hover {
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(0, 0, 0, .12);
}

// Icon styling in cards
.s_card .fa,
.card .fa.fa-3x {
    color: var(--daisy-primary, ${THEME_PRIMARY});
}

// Table improvements
.table-comparison {
    thead {
        background: var(--daisy-light-bg);
    }

    td, th {
        padding: 12px 16px;
        vertical-align: middle;
    }

    .fa-check {
        color: #28a745;
    }

    .fa-times {
        color: #dc3545;
    }
}

// CTA dark sections
.bg-dark-section {
    background: #1a1a1a;
    color: #fff;

    h2, h3, p, .lead {
        color: #fff;
    }
}

// Badge pills
.badge-feature {
    background: var(--daisy-primary, ${THEME_PRIMARY});
    color: var(--daisy-text-on-primary, ${THEME_TEXT});
    padding: 10px 20px;
    font-size: .95rem;
    font-weight: 600;
    border-radius: 50px;
    display: inline-block;
}

// Button outline variant
.btn-outline-light {
    border-color: rgba(255, 255, 255, .5);
    color: #fff;

    &:hover {
        background: rgba(255, 255, 255, .15);
        color: #fff;
    }
}

// Code blocks in download sections
.bg-dark-section pre,
.bg-dark-section code {
    background: #2d2d2d;
    color: #f8f8f2;
    border-radius: 8px;
    padding: 16px;
    font-size: .9rem;
}

// eLearning / Courses (website_slides): dark sections stay dark
.o_wslides_gradient {
    background-image: linear-gradient(120deg, #2d2d2d, #1a1a1a) !important;
    background-color: #2d2d2d !important;
}

.o_wslides_course_header {
    background-color: #2d2d2d !important;
}

.o_wslides_course_nav,
.o_wslides_course_nav .breadcrumb {
    background-color: #333333 !important;
}

.o_wslides_course_nav a,
.o_wslides_course_nav .breadcrumb-item,
.o_wslides_course_nav .breadcrumb-item a,
.o_wslides_course_nav .breadcrumb-item.active {
    color: var(--daisy-primary, ${THEME_PRIMARY}) !important;
}

.o_wslides_fs_sidebar_header {
    background-color: #2d2d2d !important;
}

.o_wslides_fs_sidebar {
    background-color: #1a1a1a !important;
}

.o_wslides_quiz_modal .tooltip-inner {
    background-color: #2d2d2d !important;
}

.o_wslides_slide_list_header {
    background-color: #f5f5f5 !important;
    color: #1a1a1a !important;
}

.o_wslides_channel_completion .progress-bar,
.o_wslides_progress .progress-bar {
    background-color: var(--daisy-primary, ${THEME_PRIMARY}) !important;
}

.o_wslides_slides_list .badge.text-bg-info,
.o_wslides_slides_list .badge.bg-info {
    background-color: var(--daisy-primary, ${THEME_PRIMARY}) !important;
    color: var(--daisy-text-on-primary, ${THEME_TEXT}) !important;
}

// Responsive: stack cards on mobile
@media (max-width: 767px) {
    section {
        padding: 48px 0;
    }

    .display-3 {
        font-size: 2rem;
    }

    .display-4 {
        font-size: 1.75rem;
    }
}
SCSS

echo "Generated: $WEBSITE_FILE"
echo ""
echo "============================================================"
echo "DaisyDo theme generated successfully!"
echo "============================================================"
