from . import daisy_agent
from . import daisy_agent_feed
from . import daisy_agent_job
from . import daisy_agent_metric
from . import daisy_ai_service
from . import daisy_go2rtc_service
from . import mail_mail
from . import mail_mail_report
from . import discuss_channel
from . import im_livechat_channel
from . import mail_thread
from . import project_task
from . import res_config_settings
