from odoo import models, fields


class MailMessage(models.Model):
    _inherit = "mail.message"

    daisy_ai_generated = fields.Boolean(
        string="AI Generated",
        default=False,
        help="Whether this message was generated by a Daisy AI agent",
    )
    daisy_ai_confidence = fields.Float(
        string="AI Confidence",
        help="Confidence score from the AI response (0-1)",
    )
    daisy_intent = fields.Char(
        string="Detected Intent",
        help="Intent detected by the AI model",
    )
    daisy_conversation_id = fields.Char(
        string="Conversation ID",
        index=True,
        help="Daisy+ chatId for multi-turn conversation continuity",
    )
