{
    "name": "Mint Service Request Forms",
    "version": "19.0.9.3.2",
    "category": "Maintenance",
    "summary": "Website forms for Mint Technology, Facilities, Graphics, and Vendor service requests",
    "author": "Mint Cannabis",
    "license": "LGPL-3",
    "depends": ["maintenance", "website", "website_slides"],
    "data": [
        "security/equipment_rules.xml",
        "data/facilities_data.xml",
        "data/graphics_data.xml",
        "data/engineering_data.xml",
        "views/maintenance_request_views.xml",
        "views/maintenance_request_sdlc_views.xml",
        "views/templates.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
